### ISSUE TITLE
SyntaxError: The requested module 'otplib' does not provide an export named 'authenticator'

### ISSUE THREAD

**Issue by hornta** [yeojz/otplib#205]
**Describe the bug**
Taken straight from the README example, when importing totp it gives syntaxerror

**To Reproduce**
1. Code `import { totp } from "otplib";` crashes

**Screenshots**

**Details (please provide any relevant information):**

- otplib version: 12.0.1
- os: win10
- browser:
- node / yarn: 12.13.1
- frameworks (if any):

**Additional context**
node is started with experimental modules flag to enable ecmascript modules

**Comment by yeojz** [comment]
Hi @hornta ! 
Thanks for the report.

If you're using experimental flag only without transpiling (eg: babel),  then you'll have to do:

```
import otplib from 'otplib';
const totp = otplib.totp;
```

**Reason:**
Currently, the module is being released as a `commonjs` module for wider platform compatibility (i.e. old node style), and thus `import {something} from pkg` work assuming transpilation is used. (TODO: I'll update the docs to reflect this.)

At this moment, since is still considered experimental on node, I've not worked it into a release yet.
