### ISSUE TITLE
5.2 RFC 6238 past time-step window support

### ISSUE THREAD

**Issue by cyclopentan** [yeojz/otplib#22]
`The validation system should compare OTPs not only with
   the receiving timestamp but also the past timestamps that are within
   the transmission delay.`

Code may change while user is entering code. For this situation system check actual and past code. No need to wait for time-window change

Add parameter for it. Suggest to set it to 1 window by default

**Comment by yeojz** [comment]
Acknowledged.

**Comment by yeojz** [comment]
With regards to this, I'll look into this over the weekend / holidays.
If you like to open a PR, that would be great too :)
Thanks!

**Comment by cyclopentan** [comment]
I tried to hotfix it, but got stuck with build. There is no `run` item, if i create folder it causes error `run is a folder`. Also there is no `build` folder according to `.gitignore`, but i can create it.

Maybe you need to builder or i need more experience in team work :)
Also why you prefer `yarn` to `npm`, what advantages it have? Can `npm` be used instead of `yarn`?

**Comment by yeojz** [comment]
@cyclopentan 
Generally, there is no `run` since it's meant to be a library (and no UI or application associated with it)
The use-cases or implementation should be checked by running the `npm run test` or `npm run test:watch`. 

Feel free to use `npm`. 
`yarn` was preferred as this library existed before `package-lock.json` was introduced in `npm`. Thus, IMO, for package maintenance, it was better.. Not much difference now.

**Comment by yeojz** [comment]
released in v8.0.1
