### ISSUE TITLE
How to use otplib with Expo?

### ISSUE THREAD

**Issue by ar-maged** [yeojz/otplib#245]
**Describe the bug**
Getting incorrect TOTPs when using `@otplib/core` & `@otplib/plugin-crypto-js` with Expo.

**To Reproduce**
1. Clone this [example](https://github.com/ar-maged/otplib-expo-example)
2. `yarn`
3. `yarn web` or `yarn ios` or `yarn android`

**Expected behavior**
Getting correct TOTPs in accordance with https://otplib.yeojz.dev or https://rootprojects.org/authenticator using the same secret.

**Screenshots**
![Screen Shot 2020-03-08 at 02 01 56](https://user-images.githubusercontent.com/11808903/76154699-dfafc280-60e0-11ea-99ef-faa53f9cb785.png)

**Details**

- otplib: `v12.0.1`
- node: `v10.15.3`
- yarn: `v1.22.1`

**Comment by ar-maged** [comment]
@yeojz And thanks a bunch for your time and effort working on this outstanding library! 👏

**Comment by yeojz** [comment]
hi @ar-maged

Thanks.

Looked at the code. The reason why it is not matching is because you are using totp instead of the authenticator methods. The difference between the two is that the keys used in authenticator are base32 encoded.

i.e. if you want to use totpToken, then you'll have to decode first  `secret -> base32decode(secret) -> totpToken`

Modification:

```js
import { keyDecoder } from '@otplib/plugin-base32-enc-dec';
```

```js
 const totp = totpToken(
  keyDecoder(secret, 'hex'),
  totpOptions({
    createDigest,
    encoding: 'hex'
  })
);
```


alternatively, you can use the authenticatorToken method provided by the library.

**Comment by ar-maged** [comment]
Outstanding! Thank you very much for the thorough explanation 👌
